### ISSUE TITLE
i always meet this error,why?

### ISSUE THREAD

**Issue by kaysonyang** [spring-cloud-samples/authserver#4]
user_cloud-oauth2-server_1 | 2016-10-22T06:16:58.659398136Z 2016-10-22 06:16:58.659  WARN 1 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.boot.autoconfigure.security.oauth2.resource.UserInfoRestTemplateFactory] is defined
user_cloud-oauth2-server_1 | 2016-10-22T06:16:58.751738128Z 2016-10-22 06:16:58.751  INFO 1 ---

**Comment by Bessonov** [comment]
Same error after upgrade from Brixton.RC2 to Camden.SR2 and Spring Boot from 1.3.6.RELEASE to 1.4.1.RELEASE.
